### ISSUE TITLE
外网shadowsocks，内网VPN

### ISSUE THREAD

**Issue by bitweng** [changlan/kytan#10]
直接连外网很容易受到干扰和被监控。有没有一种可能：在内网中有一个中转设备(或虚拟机)，中转设备上设置shadowsocks访问墙外，同时中转设备上设置VPN服务端。客户端通过VPN连到中转设备中使用。这样命令行、docker用起来就欢了

**Comment by changlan** [comment]
1. 技术上是可以的，需要在中转设备上将 kytan 的流量转发到 shadowsocks 的 socks 代理。应该不需要修改源代码。
2. 是否已经证实 kytan 比 shadowsocks 容易受到干扰？如果能提供相关数据，将很有帮助。
