### ISSUE TITLE
panicked at 'Unable to create TUN device'

### ISSUE THREAD

**Issue by Linger2** [changlan/kytan#16]
主机是OpenVZ的

**Comment by Linger2** [comment]
启动后显示net.ipv4.ip_forward = 1 然后就panick了

**Comment by changlan** [comment]
Thanks for reporting! Could you please run with environmental variable `RUST_LOG=debug` and report the traceback information?

**Comment by Linger2** [comment]
INFO:kytan::network: Working in server mode.
INFO:kytan::network: Public IP: 23.228.103.25
INFO:kytan::network: Enabling kernel's IPv4 forwarding.
INFO:kytan::utils: Enabling IPv4 Forwarding.
net.ipv4.ip_forward = 1
INFO:kytan::network: Bringing up TUN device.
thread 'main' panicked at 'Unable to create TUN device.', src/network.rs:58:19
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Linger2** [comment]
Maybe i found answer . some OpenVZ devices cant use TUN/TAP.

**Comment by changlan** [comment]
Yes, unfortunately many OpenVZ VPS do not support TUNTAP devices.
