### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by testcaoy7** [changlan/kytan#19]
I compiled kytan via git commit 2374a67.
On server  I ran "./kytan -m s -p 17115 -s pswd"
On Client I ran "./kytan -m c -p 17115 -h 11.22.33.44 -s pswd"

On server (Ubuntu 16), a TUN device was created.
On client (Linux Mint 18.2) there is no created TUN/TAP device.

**Comment by changlan** [comment]
Thanks for reporting! Could you please run with environmental variable RUST_LOG=debug and report the traceback information?
