### ISSUE TITLE
编译ring,遇错，怎么解决？

### ISSUE THREAD

**Issue by luckypoem** [changlan/kytan#23]
hi.
git clone https://github.com/changlan/kytan.git
cd kytan
cargo build --release
显示：
...
Compiling ring v0.12.1
error[E0583]: file not found for module `montgomery`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic/arithmetic.rs:15:9
   |
15 | pub mod montgomery;
   |         ^^^^^^^^^^
   |
   = help: name the file either arithmetic/montgomery.rs or arithmetic/montgomery/mod.rs inside the directory "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.12.1/src/arithmetic".
error: aborting due to previous error
error: Could not compile `ring`.
To learn more, run the command again with --verbose.
root@RegalMusty-VM:~/kytan#

**Comment by zonyitoo** [comment]
相信跟`rustc`版本有关，版本是多少？

**Comment by LuoZijun** [comment]
@zonyitoo `nightly` 版本，跟 `shadowsocks-rust` 里面那个是一样的。

**Comment by zonyitoo** [comment]
那应该就是`v0.12.1`的问题？之前那个issue就是新的rustc编不了这个。升级一下ring的版本。

**Comment by LuoZijun** [comment]
@zonyitoo 没错。

**Comment by luckypoem** [comment]
@LuoZijun 
我发现用此法curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly安装的cargo,
运行cargo build --release就会遇到我上面报告的错误。
卸载它（运行/usr/local/lib/rustlib/uninstall.sh），然后运行curl https://sh.rustup.rs -sSf | sh来安装cargo,然后运行cargo build --release就不会遇到我上面报告的错误了。

**Comment by LuoZijun** [comment]
@luckypoem 嗯，版本问题。

**Comment by luckypoem** [comment]
@LuoZijun 
不过现在虽然我在linux vps和mac机器上，都成功安装了kytan,但是按它的readme里的内容,两边都运行了
kytan:

root@yms:~# ps aux|grep kytan
root       304  0.0  0.2  12728  2224 pts/0    S+   13:13   0:00 grep kytan
root     32758  0.0  0.2  17856  2560 ?        Ss   13:12   0:00 /root/kytan/target/release/kytan --mode s -p 9527 --secret my-password
root@yms:~#

在mac上：
yudeMacBook-Air:release brite$ sudo ./kytan --mode c -p 9527 -h my-vps-ip --secret my-password
Password:
add host my-vps-ip: gateway 192.168.1.1
delete net default
add net default: gateway 10.10.10.1

然后，用浏览器翻墙（浏览器本身未设置代理），根本就翻不了，怎么回事？
你用它这个程序，能成功翻墙吗

**Comment by LuoZijun** [comment]
@luckypoem 可能是路由表没有设置好（服务器上面的）。我没用过，不太清楚。

**Comment by briansmith** [comment]
See https://twitter.com/BRIAN_____/status/955339612381093888.
