### ISSUE TITLE
Cannot build Kytan under macOS.

### ISSUE THREAD

**Issue by testcaoy7** [changlan/kytan#28]
I install Rust on my MacBook Pro.
And this is what I did:
git clone https://github.com/changlan/kytan.git
cd kytan
cargo build --release --verbose

This is what I got:

error[E0432]: unresolved import `bincode::Infinite`
  --> src/network.rs:21:39
   |
21 | use bincode::{serialize, deserialize, Infinite};
   |                                       ^^^^^^^^ no `Infinite` in the root

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
  --> src/network.rs:81:41
   |
81 |     let encoded_req_msg: Vec<u8> = try!(serialize(&req_msg, Infinite).map_err(|e| e.to_string()));
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
   --> src/network.rs:199:39
    |
199 |                     let encoded_msg = serialize(&msg, Infinite).unwrap();
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
   --> src/network.rs:293:49
    |
293 |                             let encoded_reply = serialize(&reply, Infinite).unwrap();
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
   --> src/network.rs:351:47
    |
351 |                             let encoded_msg = serialize(&msg, Infinite).unwrap();
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error: aborting due to 5 previous errors

error: Could not compile `kytan`.

Caused by:
  process didn't exit successfully: `rustc --crate-name kytan src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=0478351b1c14c8a2 -C extra-filename=-0478351b1c14c8a2 --out-dir /Users/caoqing/kytan/target/release/deps -L dependency=/Users/caoqing/kytan/target/release/deps --extern rand=/Users/caoqing/kytan/target/release/deps/librand-263d08a047275420.rlib --extern transient_hashmap=/Users/caoqing/kytan/target/release/deps/libtransient_hashmap-25d9654b759cc056.rlib --extern env_logger=/Users/caoqing/kytan/target/release/deps/libenv_logger-7ae2885606dbb51c.rlib --extern ring=/Users/caoqing/kytan/target/release/deps/libring-c974d556fc8dec09.rlib --extern serde_derive=/Users/caoqing/kytan/target/release/deps/libserde_derive-5fcdce10afe346b3.dylib --extern snap=/Users/caoqing/kytan/target/release/deps/libsnap-e8f72cd5c8651672.rlib --extern serde=/Users/caoqing/kytan/target/release/deps/libserde-3b389f9d8c49f976.rlib --extern getopts=/Users/caoqing/kytan/target/release/deps/libgetopts-65cb25f4d22508fa.rlib --extern dns_lookup=/Users/caoqing/kytan/target/release/deps/libdns_lookup-5cee9a471ee423d1.rlib --extern log=/Users/caoqing/kytan/target/release/deps/liblog-b925b1969baa5d7b.rlib --extern libc=/Users/caoqing/kytan/target/release/deps/liblibc-6ee40ee96e5eeabb.rlib --extern bincode=/Users/caoqing/kytan/target/release/deps/libbincode-9d11a29915a29943.rlib --extern mio=/Users/caoqing/kytan/target/release/deps/libmio-42098908545e0b4c.rlib -L native=/Users/caoqing/kytan/target/release/build/ring-a6eba13810706b5d/out` (exit code: 101)

**Comment by luckypoem** [comment]
@testcaoy7 
如果在mac上，不能成功编译kytan,就下载其可执行文件好了：
https://github.com/changlan/kytan/releases/download/v0.1.0/kytan-v0.1.0-x86_64-apple-darwin

**Comment by testcaoy7** [comment]
I cannot build kyatn under Ubuntu as well. Same error output.
